kawaii-dbt:
  target: dev
  outputs:

    dev:
      type: bigquery
      method: oauth
      project: hoge
      dataset: kawaii_dbt
      threads: 4
      timeout_seconds: 300
      priority: interactive
      location: US
      retries: 1