config:
  partial_parse: False
  send_anonymous_usage_stats: False

kawaii-dbt:
  target: dev
  outputs:

    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCLOUD_PROJECT') }}"
      dataset: kawaii_dbt
      threads: 4
      timeout_seconds: 300
      priority: interactive
      location: US
      retries: 1